### PR TITLE
Add announcement for SotM 2024

### PR DESCRIPTION
**Pull request by danieldegroot2**

### CODE REVIEW

**Comment by danieldegroot2** [comment]
cc: @tyrasd

**Comment by tyrasd** [comment]
thanks! ps @tomhughes https://git.openstreetmap.org/stateofthemap.git might need to be updated with this. :wink:

**Comment by tomhughes** [comment]
I don't think that's used anymore - the site is a container now but the CI job here that should have built it got suspended due to a lack of activity.

@Firefishy - shouldn't the CI run on a master branch update as well as on a timer?

**Comment by Firefishy** [comment]
> @Firefishy - shouldn't the CI run on a master branch update as well as on a timer?

Yes, meant to be handled by the `**` branch trigger. I'll dig into why it didn't run.

**Comment by Firefishy** [comment]
"_Warning: To prevent unnecessary workflow runs, scheduled workflows may be disabled automatically. [...] In a public repository, scheduled workflows are **automatically disabled when no repository activity has occurred in 60 days.**_"

**Comment by tomhughes** [comment]
Yes it got disabled and I re-enabled it but I assumed that only disabled scheduled runs rather than disabling it altogether!

It also doesn't seem to allow manual runs so I haven't been able to retrigger it manually.

**Comment by Firefishy** [comment]
I have now added manual trigger: https://github.com/openstreetmap/stateofthemap-website/commit/5a748be33f57a67b8d43434c4b0ed8ce6b0b4af0

**Pull request merged**
